on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: connect
      run: ssh ${{ secrets.SSH_URL }}
    - name: enter password
      run: ${{secrets.SSH_PASS}}
    - name: pull git
      run: cd ${{ secrets.WORK_DIR }} && git checkout ${{secrets.WORK_DIR}} && git push
    - name: cleanup
      run: rm -rf ~/.ssh
      
